services:
  database:
    container_name: database
    image: postgres:16
    restart: always
    healthcheck:
      test: ['CMD', 'pg_isready', '-q', '-d', 'reapp', '-U', 'reapp']
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
