version: '3.8'

networks:
  database_network:
    driver: bridge

services:
  database:
    container_name: database-test
    image: postgres:16
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U reapp']
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env.test.local
    ports:
      - 5433:5432
    networks:
      - database_network
