services:
  database:
    container_name: database
    image: postgres:17-alpine3.21
    restart: always
    healthcheck:
      test: ['CMD', 'pg_isready', '-q', '-d', 'reapp', '-U', 'reapp']
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    ports:
      - "5432:5432"

  redis:
    container_name: redis
    image: redis:7.4-alpine3.21
    restart: always
    ports:
      - "6379:6379"