[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs_22", "openssl"]

[phases.install]
cmds = [
  "npm install -g corepack@0.24.1",
  "corepack enable",
  "pnpm install --ignore-scripts"
]

[phases.build]
cmds = [
  "pnpm prisma generate",
  "pnpm build",
  "pnpm prune --production --ignore-scripts"
]

[start]
cmd="pnpm dlx prisma migrate deploy && node dist/src/main.js"
