name: Deploy Reapp

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Test SSH connection
        run: |
          ssh -v -i ~/.ssh/id_ed25519 ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} echo "SSH worked!"

      - name: Deploy via SSH
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            cd ${{secrets.SERVER_APP_PATH}}
            git pull origin main
            docker-compose down
            docker-compose up -d --build
          EOF

      - name: Clean up
        run: |
          rm -rf ~/.ssh/id_ed25519
          rm -rf ~/.ssh/known_hosts
        if: always()

      - name: Notify deployment success
        run: echo "Deployment to VPS successful!"
        if: success()

      - name: Notify deployment failure
        run: echo "Deployment to VPS failed!"
        if: failure()
